# Generated by Django 6.0.1 on 2026-01-29 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_contactmessage_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Franco Emanuel Salcedo', max_length=100, verbose_name='Nombre Completo')),
                ('titulo_profesional', models.CharField(default='Desarrollador Django + Especialista en Ciberseguridad', help_text="Ej: 'Desarrollador Senior' o 'Full Stack Developer'", max_length=200, verbose_name='Título Profesional')),
                ('subtitulo_header', models.CharField(default='Creo aplicaciones web seguras, escalables y profesionales', help_text='Texto que aparece debajo del nombre en el hero', max_length=300, verbose_name='Subtítulo del Header')),
                ('foto_perfil', models.ImageField(blank=True, help_text='Imagen principal del perfil (JPG o PNG, min 400x400px)', null=True, upload_to='profile/', verbose_name='Foto de Perfil')),
                ('descripcion_corta', models.CharField(default='Desarrollo web con seguridad integrada desde el primer día', help_text='Texto para cards y meta descripciones', max_length=200, verbose_name='Descripción Corta')),
                ('bio', models.TextField(default='Soy un desarrollador apasionado por crear soluciones web seguras y escalables.', help_text="Texto que aparece en la sección 'Sobre mí'", verbose_name='Biografía Completa')),
                ('filosofia', models.TextField(default='Creo que la seguridad no es un add-on, es un principio fundamental.', help_text="Blockquote en la sección 'Sobre mí'", verbose_name='Filosofía de Desarrollo')),
                ('tecnologias', models.TextField(default='Django, Python, PostgreSQL, REST APIs, Docker, Linux', help_text='Separadas por coma o salto de línea', verbose_name='Tecnologías Principales')),
                ('email', models.EmailField(default='franco@example.com', help_text='Email de contacto principal', max_length=254, verbose_name='Email')),
                ('telefono', models.CharField(blank=True, default='+34 600 000 000', help_text='Formato: +34 600 000 000', max_length=20, verbose_name='Teléfono')),
                ('ciudad', models.CharField(blank=True, default='España', help_text='Ubicación geográfica', max_length=100, verbose_name='Ciudad/País')),
                ('github_url', models.URLField(blank=True, default='https://github.com/franchesemanuel', help_text='URL completa a tu perfil de GitHub', verbose_name='GitHub')),
                ('linkedin_url', models.URLField(blank=True, default='https://linkedin.com/in/franco', help_text='URL completa a tu perfil de LinkedIn', verbose_name='LinkedIn')),
                ('twitter_url', models.URLField(blank=True, default='', help_text='URL completa a tu perfil de Twitter', verbose_name='Twitter/X')),
                ('cv_url', models.URLField(blank=True, default='', help_text='URL a tu CV descargable', verbose_name='CV/Currículum')),
                ('mostrar_blog', models.BooleanField(default=False, verbose_name='¿Mostrar sección Blog?')),
                ('mostrar_testimonios', models.BooleanField(default=False, verbose_name='¿Mostrar sección Testimonios?')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Perfil Activo?')),
            ],
            options={
                'verbose_name': 'Perfil del Desarrollador',
                'verbose_name_plural': 'Perfil del Desarrollador',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título del Proyecto')),
                ('slug', models.SlugField(help_text='URL amigable (ej: mi-proyecto-web)', unique=True, verbose_name='Slug')),
                ('descripcion_corta', models.CharField(help_text='Se muestra en la tarjeta del proyecto', max_length=300, verbose_name='Descripción Corta')),
                ('descripcion_completa', models.TextField(blank=True, help_text='Descripción detallada del proyecto (opcional)', verbose_name='Descripción Completa')),
                ('imagen', models.ImageField(help_text='Dimensiones recomendadas: 800x600px', upload_to='projects/', verbose_name='Imagen del Proyecto')),
                ('tecnologias', models.CharField(help_text='Separadas por coma. Ej: Django, PostgreSQL, Docker', max_length=300, verbose_name='Tecnologías Utilizadas')),
                ('demo_url', models.URLField(blank=True, help_text='URL donde se puede ver el proyecto en vivo', verbose_name='Link Demo/Live')),
                ('github_url', models.URLField(blank=True, help_text='URL del repositorio en GitHub', verbose_name='Link GitHub')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Proyectos con número menor aparecen primero', verbose_name='Orden de aparición')),
                ('visible', models.BooleanField(default=True, verbose_name='¿Visible en portafolio?')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['orden', '-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icono', models.CharField(help_text='Ej: fas fa-code, fas fa-shield-alt', max_length=100, verbose_name='Icono FontAwesome')),
                ('nombre', models.CharField(help_text='Ej: Desarrollo Web', max_length=100, verbose_name='Nombre del Servicio')),
                ('descripcion', models.TextField(help_text='Descripción del servicio', verbose_name='Descripción')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden de aparición')),
                ('visible', models.BooleanField(default=True, verbose_name='¿Visible?')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_sitio', models.CharField(default='Franco Emanuel - Desarrollador Django + Ciberseguridad', max_length=100, verbose_name='Título del Sitio')),
                ('descripcion_sitio', models.CharField(default='Portfolio profesional de desarrollador Django especializado en ciberseguridad', max_length=160, verbose_name='Descripción (Meta)')),
                ('titulo_seccion_proyectos', models.CharField(default='Mis Proyectos', max_length=200, verbose_name='Título Sección Proyectos')),
                ('descripcion_seccion_proyectos', models.TextField(blank=True, default='Proyectos que muestran mi expertise en desarrollo seguro y escalable', verbose_name='Descripción Sección Proyectos')),
                ('titulo_seccion_servicios', models.CharField(default='¿Qué Ofrezco?', max_length=200, verbose_name='Título Sección Servicios')),
                ('descripcion_seccion_servicios', models.TextField(blank=True, default='Servicios profesionales para tu proyecto', verbose_name='Descripción Sección Servicios')),
                ('texto_footer', models.TextField(default='© 2026 Franco Emanuel Salcedo. Todos los derechos reservados.', help_text='Texto que aparece al pie de página', verbose_name='Texto Footer')),
                ('mostrar_projects', models.BooleanField(default=True, verbose_name='¿Mostrar sección Proyectos?')),
                ('mostrar_services', models.BooleanField(default=True, verbose_name='¿Mostrar sección Servicios?')),
                ('mostrar_contact', models.BooleanField(default=True, verbose_name='¿Mostrar formulario de contacto?')),
                ('google_analytics_id', models.CharField(blank=True, default='', max_length=50, verbose_name='Google Analytics ID')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Configuración del Sitio',
                'verbose_name_plural': 'Configuración del Sitio',
            },
        ),
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Mensaje de Contacto', 'verbose_name_plural': 'Mensajes de Contacto'},
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='leido',
            field=models.BooleanField(default=False, verbose_name='¿Leído?'),
        ),
    ]
